---
version: "3"

output: prefixed

vars:
  REPOSITORY_SUBTYPE: desktop
  REPOSITORY_TYPE: packer

includes:
  build: ./.common/taskfiles-role/Taskfile-build.yml
  common: ./.common/taskfiles-role/Taskfile-common.yml
  fix: ./.common/taskfiles-role/Taskfile-fix.yml
  lint: ./.common/taskfiles-role/Taskfile-lint.yml
  packer: ./.common/taskfiles-role/Taskfile-packer.yml
  security: ./.common/taskfiles-role/Taskfile-security.yml
  software: ./.common/taskfiles-role/Taskfile-{{OS}}.yml
